/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package great;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        administrarIlegales.cargarArchivo();
        for (int i = 0; i < aeropuerto.getCap(); i++) {
            aeropuerto.entrar(new Avion(i));
        }
        Image img = Toolkit.getDefaultToolkit().createImage("./trump2.jpg").getScaledInstance(1400, 700, 0);
        this.lb_imgPrincipal.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registro = new javax.swing.JDialog();
        lb_nombre = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        lb_fecha = new javax.swing.JLabel();
        tf_nacionalidad = new javax.swing.JTextField();
        lb_nacionalidad1 = new javax.swing.JLabel();
        jc_date = new com.toedter.calendar.JDateChooser();
        lb_raza = new javax.swing.JLabel();
        js_raza = new javax.swing.JSpinner();
        lb_pais = new javax.swing.JLabel();
        tf_pais = new javax.swing.JTextField();
        jb_agregarIlegal = new javax.swing.JButton();
        lb_imagenRegistro = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jd_abordaje = new javax.swing.JDialog();
        lb_progreso = new javax.swing.JLabel();
        barraProgreso1 = new javax.swing.JProgressBar();
        jb_abordarAvion = new javax.swing.JButton();
        jc_ilegales = new javax.swing.JComboBox<>();
        lb_imgPrincipal = new javax.swing.JLabel();
        jb_menu = new javax.swing.JMenuBar();
        jm_menu1 = new javax.swing.JMenu();
        ji_registro = new javax.swing.JMenuItem();
        ji_abordaje = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jd_registro.setTitle("Registro Ilegales");

        lb_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_nombre.setText("Nombre: ");
        lb_nombre.setOpaque(true);

        lb_fecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_fecha.setText("Fecha Nacimiento: ");
        lb_fecha.setOpaque(true);

        lb_nacionalidad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_nacionalidad1.setText("Nacionalidad:");
        lb_nacionalidad1.setOpaque(true);

        lb_raza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_raza.setText("Raza:");
        lb_raza.setOpaque(true);

        js_raza.setModel(new javax.swing.SpinnerListModel(new String[] {"Hispano", "Afroasiático", "Indioeuropeo", "Níger-Congo"}));

        lb_pais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_pais.setText("País Origen");
        lb_pais.setOpaque(true);

        jb_agregarIlegal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_agregarIlegal.setText("Agregar");
        jb_agregarIlegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarIlegalActionPerformed(evt);
            }
        });

        lb_imagenRegistro.setOpaque(true);

        javax.swing.GroupLayout jd_registroLayout = new javax.swing.GroupLayout(jd_registro.getContentPane());
        jd_registro.getContentPane().setLayout(jd_registroLayout);
        jd_registroLayout.setHorizontalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jb_agregarIlegal))
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_pais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_nacionalidad1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_raza, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jc_date, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(js_raza)
                            .addComponent(tf_pais))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(lb_imagenRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jd_registroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jc_date, tf_nacionalidad, tf_nombre});

        jd_registroLayout.setVerticalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_imagenRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nombre)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nacionalidad1)
                            .addComponent(tf_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_fecha)
                            .addComponent(jc_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_raza)
                            .addComponent(js_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_pais)
                            .addComponent(tf_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jb_agregarIlegal)))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jd_registroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lb_nombre, tf_nombre});

        jd_registroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jc_date, lb_fecha, lb_nacionalidad1, tf_nacionalidad});

        jd_registroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lb_pais, lb_raza});

        jd_registroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {js_raza, tf_pais});

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jd_abordaje.setTitle("Aeropuerto");

        lb_progreso.setText("Abordaje");

        jb_abordarAvion.setText("Abordar Avion");
        jb_abordarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_abordarAvionActionPerformed(evt);
            }
        });

        jc_ilegales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jd_abordajeLayout = new javax.swing.GroupLayout(jd_abordaje.getContentPane());
        jd_abordaje.getContentPane().setLayout(jd_abordajeLayout);
        jd_abordajeLayout.setHorizontalGroup(
            jd_abordajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_abordajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_abordajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraProgreso1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addGroup(jd_abordajeLayout.createSequentialGroup()
                        .addComponent(lb_progreso)
                        .addGap(0, 165, Short.MAX_VALUE))
                    .addComponent(jc_ilegales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_abordarAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jd_abordajeLayout.setVerticalGroup(
            jd_abordajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_abordajeLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lb_progreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barraProgreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jc_ilegales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jb_abordarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("America Great");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jb_menu.setBackground(new java.awt.Color(255, 0, 0));
        jb_menu.setBorder(null);
        jb_menu.setForeground(new java.awt.Color(255, 0, 0));
        jb_menu.setBorderPainted(false);

        jm_menu1.setText("File");

        ji_registro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        ji_registro.setText("Registro");
        ji_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ji_registroActionPerformed(evt);
            }
        });
        jm_menu1.add(ji_registro);

        ji_abordaje.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        ji_abordaje.setText("Abordaje");
        ji_abordaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ji_abordajeActionPerformed(evt);
            }
        });
        jm_menu1.add(ji_abordaje);

        jb_menu.add(jm_menu1);

        jMenu2.setText("Edit");
        jb_menu.add(jMenu2);

        setJMenuBar(jb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_imgPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_imgPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ji_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ji_registroActionPerformed
        // TODO add your handling code here:
        Image img = Toolkit.getDefaultToolkit().createImage("./trump1.jpg").getScaledInstance(220, 293, 0);
        this.lb_imagenRegistro.setIcon(new ImageIcon(img));
        jd_registro.setModal(true);
        jd_registro.pack();
        jd_registro.setLocationRelativeTo(this);
        jd_registro.setVisible(true);

    }//GEN-LAST:event_ji_registroActionPerformed

    private void jb_agregarIlegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarIlegalActionPerformed
        // TODO add your handling code here:
        String fecha = ((JTextField) jc_date.getDateEditor().getUiComponent()).getText();
        Ilegal ilegal = new Ilegal(tf_nombre.getText(), tf_nacionalidad.getText(), fecha, js_raza.getValue().toString(), tf_pais.getText(), false);
        administrarIlegales.write(ilegal);
        //administrarIlegales.getList().add(ilegal);
    }//GEN-LAST:event_jb_agregarIlegalActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        administrarIlegales.refresh();
    }//GEN-LAST:event_formWindowClosed

    private void ji_abordajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ji_abordajeActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < administrarIlegales.getList().getSize(); i++) {
            model.addElement(administrarIlegales.getList().get(i));
        }
        jc_ilegales.setModel(model);
        jd_abordaje.setModal(true);
        jd_abordaje.pack();
        jd_abordaje.setLocationRelativeTo(this);
        jd_abordaje.setVisible(true);
    }//GEN-LAST:event_ji_abordajeActionPerformed

    private void jb_abordarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_abordarAvionActionPerformed
        // TODO add your handling code here:
        Ilegal temp = (Ilegal) jc_ilegales.getSelectedItem();
        if (!temp.isDeported()) {
            aeropuerto.Abord(temp);
            temp.changeStatus(true);
            JOptionPane.showMessageDialog(null, "Great!!");
            if (((Avion)aeropuerto.ver()).isFull()) {
                Viaje.Queue(aeropuerto.salir());
            }
        } else {
            JOptionPane.showMessageDialog(null, "El Ilegal ya ha sido deportado!", "Error", JOptionPane.WARNING_MESSAGE);
        }
        for (int i = 0; i < administrarIlegales.getList().size; i++) {
            System.out.println(((Ilegal)administrarIlegales.getList().get(i)).isDeported());
        }
        administrarIlegales.refresh();
    }//GEN-LAST:event_jb_abordarAvionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JButton jb_abordarAvion;
    private javax.swing.JButton jb_agregarIlegal;
    private javax.swing.JMenuBar jb_menu;
    private com.toedter.calendar.JDateChooser jc_date;
    private javax.swing.JComboBox<String> jc_ilegales;
    private javax.swing.JDialog jd_abordaje;
    private javax.swing.JDialog jd_registro;
    private javax.swing.JMenuItem ji_abordaje;
    private javax.swing.JMenuItem ji_registro;
    private javax.swing.JMenu jm_menu1;
    private javax.swing.JSpinner js_raza;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_imagenRegistro;
    private javax.swing.JLabel lb_imgPrincipal;
    private javax.swing.JLabel lb_nacionalidad1;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_pais;
    private javax.swing.JLabel lb_progreso;
    private javax.swing.JLabel lb_raza;
    private javax.swing.JTextField tf_nacionalidad;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_pais;
    // End of variables declaration//GEN-END:variables
    AdminIlegales administrarIlegales = new AdminIlegales("./ilegales.bin");
    Aeropuerto aeropuerto = new Aeropuerto();
    Queue Viaje = new Queue();

}
